version: '3.7'
services:
  redis:
    image: redis:7.0-rc1-alpine3.15
    ports:
      - '6379:6379'

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3370:3306
    environment:
      MYSQL_ROOT_PASSWORD: wMT9ABAAmyrju3wF
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PORT=3306
      - PMA_PASSWORD=wMT9ABAAmyrju3wF
    depends_on:
      - mysql
    ports:
      - 8870:80
volumes:
  mysql:
